# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install --project-directory=Example

language: swift
osx_image: xcode8.3
xcode_workspace: Example/NumericAnimatedLabel.xcworkspace
xcode_scheme: NumericAnimatedLabel-Example
xcode_sdk: iphonesimulator10.3
podfile: Example/Podfile
branches:
  only:
    - master
